[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PySaxPower"
version = "2.0.0"
description = "Python package to read and write data from/to SAX Power Home Plus batteries."
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
    {name = "Hannes"}
]
dependencies = [
    "pymodbus==3.15.0"
]

[project.urls]
Homepage = "https://github.com/Hans-4/pysaxpower"